#  - Branching & Commit Strategy

**Generated by Proto Gear v0.3**
**Project**: 
**Ticket Prefix**: PROTO

---

## Overview

This document defines the branching model and commit conventions for . Following these conventions ensures consistency across all contributors (human and AI).

---

## Branch Structure

### Main Branches

#### `main`
- **Purpose**: Production-ready code
- **Status**: Always stable, deployable
- **Protection**: No direct commits
- **Pull Requests**: Required for merging

#### `development`
- **Purpose**: Integration branch for development
- **Status**: Should always build and pass tests
- **Merges from**: Feature, bugfix branches
- **Merges to**: `main` (via pull request)

### Working Branches

#### Feature Branches: `feature/PROTO-{number}-{description}`

**Examples**:
```
feature/PROTO-001-implement-auth
feature/PROTO-002-add-dashboard
```

**Use for**:
- New features
- Enhancements
- Non-urgent improvements

**Lifecycle**:
1. Branch from: `development`
2. Work on feature
3. Merge to: `development` (via pull request)
4. Delete after merge

#### Bugfix Branches: `bugfix/PROTO-{number}-{description}`

**Examples**:
```
bugfix/PROTO-010-fix-login-error
bugfix/PROTO-011-resolve-crash
```

**Use for**:
- Bug fixes
- Error corrections
- Issue resolution

**Lifecycle**:
1. Branch from: `development`
2. Fix bug
3. Add regression test
4. Merge to: `development` (via pull request)
5. Delete after merge

#### Hotfix Branches: `hotfix/v{version}-{issue}`

**Examples**:
```
hotfix/v1.2.1-critical-security-fix
hotfix/v1.2.1-data-loss-bug
```

**Use for**:
- Critical production bugs
- Security vulnerabilities
- Data loss issues

**Lifecycle**:
1. Branch from: `main`
2. Apply minimal fix
3. Merge to: `main` AND `development`
4. Tag new version immediately
5. Delete after merge

---

## Commit Message Convention

### Format

```
<type>(<scope>): <subject>

<body>

<footer>
```

### Types

| Type | Description | Example |
|------|-------------|---------|
| `feat` | New feature | `feat(auth): add login functionality` |
| `fix` | Bug fix | `fix(api): handle null response` |
| `docs` | Documentation | `docs(readme): update setup instructions` |
| `style` | Code style | `style: apply formatting` |
| `refactor` | Refactoring | `refactor(db): optimize queries` |
| `perf` | Performance | `perf(api): cache responses` |
| `test` | Tests | `test(auth): add login tests` |
| `build` | Build system | `build: update dependencies` |
| `ci` | CI/CD | `ci: add test workflow` |
| `chore` | Maintenance | `chore: update version` |

### Subject Guidelines

- Use imperative mood: "add" not "added"
- Don't capitalize first letter
- No period at the end
- Maximum 50 characters

### Body (Optional)

- Wrap at 72 characters
- Explain what and why, not how
- Separate from subject with blank line

### Footer (When Applicable)

- Reference issues: `Closes PROTO-XXX`
- Breaking changes: `BREAKING CHANGE: description`

### Examples

```
feat(dashboard): add user analytics widget

Add real-time analytics widget showing active users,
session duration, and conversion metrics.

Closes PROTO-042
```

```
fix(api): handle timeout errors gracefully

API calls were failing without proper error handling
when external service timed out.

Fixes PROTO-089
```

---

## Workflow for Contributors

### Before Starting Work

1. **Check current branch**: Verify you're on `development`
2. **Pull latest changes**: `git pull origin development`
3. **Create feature branch**: `git checkout -b feature/PROTO-XXX-description`
4. **Verify branch name**: Follows convention exactly

### During Development

1. **Make focused commits**: One logical change per commit
2. **Write clear commit messages**: Follow convention above
3. **Test before committing**: Ensure code works
4. **Commit frequently**: Small commits are better
5. **Push to remote**: `git push -u origin your-branch-name` (enables backup)

### Before Merging

1. **Review all changes**: `git diff development`
2. **Ensure tests pass**: Run your test suite
3. **Update from development**: `git rebase development` (if behind)

4. **Push to remote**: `git push -u origin feature-branch`
5. **Create pull request**: On GitHub/GitLab


---

## Working with AI Agents

### Conventions for AI Assistants

When working with AI assistants (Claude, GPT, etc.), ensure they:

✅ **DO**:
- Create branches for all work
- Use descriptive branch names
- Write clear commit messages following convention
- Reference ticket numbers (PROTO-XXX)
- Test changes before committing{{REMOTE_PUSH_REGULARLY}}
- Update documentation when behavior changes

❌ **DON'T**:
- Commit directly to `main`
- Commit directly to `development` for features
- Use vague commit messages
- Skip testing
- Make huge commits without breaking them down{{REMOTE_FORCE_PUSH}}

### AI Agent Communication

AI agents should communicate their approach:

```markdown
I'm going to:
1. Create branch: feature/PROTO-XXX-feature-name
2. Implement the feature
3. Write tests
4. Commit with message: "feat(scope): add feature"
5. Push to remote: git push -u origin feature/branch

6. Create pull request on GitHub/GitLab

Does this approach work for you?
```

## Working with Remote Repository

This project has a remote repository configured (origin).

### Push Regularly
```bash
# Push your branch to backup work
git push -u origin feature/{{TICKET_PREFIX}}-XXX-description

# Check remote status
git branch -vv
```

### Creating Pull Requests
1. Push your branch to remote
2. Go to your repository on GitHub/GitLab
3. Create pull request from your branch to `{{DEV_BRANCH}}`
4. Request review if required
5. Merge after approval

---

## Ticket Numbering

### Format: `PROTO-{number}`

- Start from: `PROTO-001`
- Increment sequentially
- Track in: GitHub Issues or PROJECT_STATUS.md

### Examples
```
PROTO-001: Implement user authentication
PROTO-002: Add dashboard widgets
PROTO-003: Fix login redirect issue
```

---

## Quick Reference

```
BRANCH PATTERNS:
feature/PROTO-XXX-description    → New features
bugfix/PROTO-XXX-description     → Bug fixes
hotfix/vX.Y.Z-issue                          → Critical fixes

COMMIT FORMAT:
<type>(<scope>): <subject>

TYPES:
feat, fix, docs, style, refactor, perf, test, build, ci, chore

ALWAYS:
✅ Branch from development
✅ Use descriptive names
✅ Write clear commits
✅ Test before committing
✅ Push to remote regularly

✅ Create PR for review

NEVER:
❌ Commit to main directly
❌ Use vague messages
❌ Skip testing
❌ Force push to shared branches
```

---

**Document Status**: Active
**Generated**: 2025-11-05
**Maintained By**:  Team
**Tool**: Proto Gear AI Agent Framework

---

*This branching strategy was generated by Proto Gear to help maintain consistency in AI-assisted development. Customize this file to match your team's specific needs.*
