#!/usr/bin/env python3
"""
Proto Gear - AI Agent Framework for Project Development
Main entry point for integrating AI-powered development workflows
"""

from pathlib import Path

# Import version from package
from . import __version__

# Import UI helper for consistent terminal output
from .ui_helper import Colors

# Try to import enhanced wizard module
try:
    from .modules.engineering.interactive_wizard import (
        run_enhanced_wizard,
        run_incremental_wizard,
        QUESTIONARY_AVAILABLE,
        RICH_AVAILABLE,
    )

    ENHANCED_WIZARD_AVAILABLE = True
except ImportError:
    ENHANCED_WIZARD_AVAILABLE = False
    QUESTIONARY_AVAILABLE = False
    RICH_AVAILABLE = False
    run_incremental_wizard = None

# Import CLI command handlers

# File handling helpers

# Project / environment / git detection lives in detection.py
# (PROTO-042, ADR-001 Phase A). Re-exported here so direct imports and the
# proto_gear_pkg.proto_gear.* patch targets used by the tests keep working.
from .modules.engineering.detection import (
    detect_existing_environment,
    detect_project_structure,
    detect_git_config,
)

# Template generation + capability installation live in templates.py
# (PROTO-042, ADR-001 Phase A; engineering-module-specific per ADR-001).
# Re-exported here so setup_agent_framework_only / run_simple_protogear_init
# and the proto_gear_pkg.proto_gear.* patch targets keep working unchanged.
from .modules.engineering.templates import (
    safe_write_file,
    generate_branching_doc,
    discover_available_templates,
    generate_project_template,
    copy_capability_templates,
)

# Terminal presentation helpers (logo, splash, help, input) live in
# presentation.py (PROTO-042, ADR-001 Phase A). Re-exported here so
# `from proto_gear_pkg.proto_gear import show_help` etc. and the
# `proto_gear_pkg.proto_gear.*` patch targets keep working unchanged.
from .presentation import (
    get_logo_v1,
    PROTO_GEAR_LOGOS,
    clear_screen,
    safe_input,
    print_centered,
    show_splash_screen,
    show_help,
    print_farewell,
)


def setup_agent_framework_only(
    dry_run=False,
    force=False,
    with_branching=False,
    ticket_prefix=None,
    with_capabilities=False,
    capabilities_config=None,
    with_all=False,
    core_templates=None,
    project_description=None,
):
    """Set up ProtoGear agent framework in existing project"""
    from datetime import datetime

    print(f"\n{Colors.CYAN}Agent Framework Setup{Colors.ENDC}")
    print("-" * 30)

    current_dir = Path(".")
    print(f"Current directory: {current_dir.absolute()}")

    # Detect project structure
    project_info = detect_project_structure(current_dir)

    if project_info["detected"]:
        print(f"Detected: {project_info['type']} project")
        if project_info.get("framework"):
            print(f"Framework: {project_info['framework']}")

    if not dry_run:
        try:
            files_created = []

            # Write PROJECT_SPECIFICATIONS.md stub from user-provided description
            if project_description:
                specs_dest = current_dir / "PROJECT_SPECIFICATIONS.md"
                stub_content = f"""# PROJECT_SPECIFICATIONS.md

## Project Overview

{project_description}

## Goals

<!-- What are the primary goals of this project? -->

## Architecture

<!-- High-level architecture decisions and patterns -->
<!-- See PROJECT_ARCHITECTURE.md for detailed architecture (extracted by AI agent) -->

## Key Features

<!-- List main features and user stories -->

## Tech Stack

<!-- Languages, frameworks, libraries, tools -->

## Constraints & Requirements

<!-- Non-functional requirements, limitations, compliance needs -->

---

> **Note for AI Agents**: This stub was generated by Proto Gear from a brief description.
> Before starting feature work, work with the user to fill in the sections above,
> then extract all architecture decisions into `PROJECT_ARCHITECTURE.md`.
> `PROJECT_ARCHITECTURE.md` supersedes any generic `ARCHITECTURE.md` template.
"""
                try:
                    specs_dest.write_text(stub_content, encoding="utf-8")
                    files_created.append("PROJECT_SPECIFICATIONS.md")
                except (IOError, OSError) as e:
                    print(
                        f"{Colors.YELLOW}Warning: Could not create specifications stub: {e}{Colors.ENDC}"
                    )

            # Determine ticket prefix
            if not ticket_prefix:
                # Try to derive from project name
                project_name = (
                    current_dir.name.upper().replace("-", "").replace("_", "")[:6]
                )
                ticket_prefix = project_name if project_name else "PROJ"

            # Optionally create BRANCHING.md
            branching_reference = ""
            if with_branching:
                git_config = detect_git_config()
                branching_content = generate_branching_doc(
                    current_dir.name,
                    ticket_prefix,
                    git_config,
                    datetime.now().strftime("%Y-%m-%d"),
                )

                if branching_content:
                    branching_file = current_dir / "BRANCHING.md"
                    action, written = safe_write_file(
                        branching_file,
                        branching_content,
                        dry_run=dry_run,
                        force=force,
                        interactive=True,
                    )
                    if written or action == "would_create":
                        files_created.append("BRANCHING.md")
                    branching_reference = f"\n> **📋 Branching Strategy**: See [BRANCHING.md](BRANCHING.md) for Git workflow and commit conventions\n"

            # Create AGENTS.md (only if doesn't exist or explicitly selected)
            agents_file = current_dir / "AGENTS.md"
            should_create_agents = not agents_file.exists() or (  # Fresh install
                core_templates
                and "AGENTS"
                in [
                    t.replace(".md", "")
                    for t in (
                        core_templates if isinstance(core_templates, list) else []
                    )
                ]
            )  # Explicitly selected

            if should_create_agents:
                # Use template-based generation instead of hardcoded content
                template_context = {
                    "PROJECT_NAME": current_dir.name,
                    "TICKET_PREFIX": ticket_prefix,
                    "DATE": datetime.now().strftime("%Y-%m-%d"),
                    "YEAR": datetime.now().strftime("%Y"),
                    "VERSION": __version__,
                    "PROJECT_TYPE": project_info.get("type", "Unknown"),
                    "FRAMEWORK": project_info.get("framework", "Unknown"),
                }

                output_file, action = generate_project_template(
                    "AGENTS",
                    current_dir,
                    template_context,
                    dry_run=dry_run,
                    force=force,
                    interactive=True,
                )

                if output_file or action == "would_create":
                    files_created.append("AGENTS.md")

            # Create SESSION_HANDOFF.md (only if doesn't exist — agent-owned content, never clobber)
            handoff_file = current_dir / "SESSION_HANDOFF.md"
            if not handoff_file.exists():
                handoff_content = f"""# SESSION_HANDOFF — {current_dir.resolve().name}

> **Read this before anything else.** This file captures what's true right now.
> **At session end**: replace the contents entirely — do not append.
> This is a rolling "current state" snapshot, not a log.

## What Just Shipped

*No previous session — starting fresh.*

## Pending / In Progress

*Nothing pending.*

## Conventions In Force

*No session-specific conventions. See AGENTS.md for standing rules.*

## Open Questions

*None.*

---
*Agent-maintained. Replace entirely at session end.*
"""
                action, written = safe_write_file(
                    handoff_file,
                    handoff_content,
                    dry_run=dry_run,
                    force=force,
                    interactive=True,
                )
                if written or action == "would_create":
                    files_created.append("SESSION_HANDOFF.md")

            # Create PROJECT_STATUS.md (only if doesn't exist or explicitly selected)
            status_file = current_dir / "PROJECT_STATUS.md"
            should_create_status = not status_file.exists() or (  # Fresh install
                core_templates
                and "PROJECT_STATUS"
                in [
                    t.replace(".md", "")
                    for t in (
                        core_templates if isinstance(core_templates, list) else []
                    )
                ]
            )  # Explicitly selected

            if should_create_status:
                status_content = f"""# PROJECT STATUS - {current_dir.name}

> **Single Source of Truth** for project state

## Current State

```yaml
project_phase: "Initialized"
protogear_enabled: true
framework: "{project_info.get('framework', 'Unknown')}"
project_type: "{project_info.get('type', 'Unknown')}"
initialization_date: "{datetime.now().strftime('%Y-%m-%d')}"
current_sprint: null
```

## 🎫 Active Tickets
*No active tickets yet - ProtoGear will track development progress here*

## ✅ Completed Tickets
- INIT-001: ProtoGear Agent Framework integrated

## Project Analysis

| Component | Status | Notes |
|-----------|--------|-------|
| ProtoGear Integration | Complete | Agent framework active |
| Project Structure | Analyzed | {len(project_info.get('directories', []))} directories detected |

## Recent Updates
- {datetime.now().strftime('%Y-%m-%d')}: ProtoGear Agent Framework integrated

---
*Maintained by ProtoGear Agent Framework*
"""
                action, written = safe_write_file(
                    status_file,
                    status_content,
                    dry_run=dry_run,
                    force=force,
                    interactive=True,
                )
                if written or action == "would_create":
                    files_created.append("PROJECT_STATUS.md")

            # Generate additional templates based on selections
            template_context = {
                "PROJECT_NAME": current_dir.name,
                "TICKET_PREFIX": ticket_prefix,
                "DATE": datetime.now().strftime("%Y-%m-%d"),
                "YEAR": datetime.now().strftime("%Y"),
                "VERSION": __version__,
            }

            templates_to_generate = []

            # Priority 1: Use core_templates if provided (from wizard)
            if core_templates:
                if isinstance(core_templates, dict):
                    # Dict format: {template_name: bool}
                    for template_name, should_generate in core_templates.items():
                        if should_generate and template_name not in [
                            "AGENTS",
                            "PROJECT_STATUS",
                            "SESSION_HANDOFF",
                        ]:
                            # Skip if already created (e.g., BRANCHING from with_branching flag)
                            if f"{template_name}.md" not in files_created:
                                templates_to_generate.append(template_name)
                elif isinstance(core_templates, list):
                    # List format from incremental wizard: ['BRANCHING.md', 'TESTING.md']
                    for template in core_templates:
                        template_name = template.replace(".md", "")
                        if template_name not in [
                            "AGENTS",
                            "PROJECT_STATUS",
                            "SESSION_HANDOFF",
                        ]:
                            # Skip if already created
                            if template not in files_created:
                                templates_to_generate.append(template_name)

            # Priority 2: Handle --all flag (CLI)
            elif with_all:
                templates_to_generate.extend(
                    [
                        "TESTING",
                        "BRANCHING",
                        "CONTRIBUTING",
                        "SECURITY",
                        "ARCHITECTURE",
                        "CODE_OF_CONDUCT",
                    ]
                )

            # Priority 3: Legacy behavior for with_branching
            elif with_branching:
                templates_to_generate.append("TESTING")
                if "BRANCHING" not in [f.replace(".md", "") for f in files_created]:
                    templates_to_generate.append("BRANCHING")

            # Generate all selected templates
            for template_name in templates_to_generate:
                output_file, action = generate_project_template(
                    template_name,
                    current_dir,
                    template_context,
                    dry_run=dry_run,
                    force=force,
                    interactive=True,
                )

                if output_file or action == "would_create":
                    files_created.append(f"{template_name}.md")

            # Create capabilities if requested
            if with_capabilities:
                capability_result = copy_capability_templates(
                    current_dir,
                    current_dir.name,
                    dry_run=False,
                    capabilities_config=capabilities_config,
                )

                if capability_result["status"] == "success":
                    files_created.extend(capability_result["files_created"])
                    print(
                        f"{Colors.GREEN}+ Capability system created in .proto-gear/{Colors.ENDC}"
                    )
                elif capability_result["status"] == "warning":
                    print(
                        f"{Colors.YELLOW}! {capability_result['errors'][0]}{Colors.ENDC}"
                    )
                else:
                    print(
                        f"{Colors.YELLOW}! Capability creation had issues: {capability_result.get('errors')}{Colors.ENDC}"
                    )

            # Generate AGENT_CONTEXT.md and mirror managed block into host config files
            try:
                from .module_core import sync_context as sync_context_module

                sync_results = sync_context_module.sync_context(
                    current_dir, dry_run=False
                )
                if "error" not in sync_results:
                    for path_str, action in sync_results.items():
                        if action in ("created", "updated"):
                            files_created.append(path_str)
                    print(
                        f"{Colors.GREEN}+ Agent Context synced (AGENT_CONTEXT.md + host configs){Colors.ENDC}"
                    )
            except Exception as e:
                print(f"{Colors.YELLOW}! Agent Context sync failed: {e}{Colors.ENDC}")

            return {
                "status": "success",
                "files_created": files_created,
                "mode": "agent-framework-only",
            }

        except Exception as e:
            return {"status": "error", "error": str(e)}
    else:
        print(f"\n{Colors.YELLOW}Dry run - files that would be created:{Colors.ENDC}")
        print("  - AGENTS.md (AI agent integration guide)")
        print("  - PROJECT_STATUS.md (project state tracker)")
        if with_branching:
            print("  - BRANCHING.md (Git workflow and commit conventions)")

        # Show additional templates based on selections
        templates_shown = []

        # Priority 1: Use core_templates if provided (from wizard)
        if core_templates and isinstance(core_templates, dict):
            for template_name, should_generate in core_templates.items():
                if should_generate and template_name not in [
                    "AGENTS",
                    "PROJECT_STATUS",
                    "BRANCHING",
                ]:
                    templates_shown.append(template_name)

        # Priority 2: Handle --all flag (CLI)
        elif with_all:
            templates_shown = [
                "TESTING",
                "CONTRIBUTING",
                "SECURITY",
                "ARCHITECTURE",
                "CODE_OF_CONDUCT",
            ]
            if with_branching:
                # BRANCHING already shown above
                pass
            else:
                templates_shown.insert(0, "BRANCHING")

        # Show template descriptions
        template_descriptions = {
            "TESTING": "TDD patterns and best practices",
            "BRANCHING": "Git workflow and commit conventions",
            "CONTRIBUTING": "Contribution guidelines",
            "SECURITY": "Security policy and vulnerability reporting",
            "ARCHITECTURE": "System design documentation",
            "CODE_OF_CONDUCT": "Community guidelines",
        }

        for template_name in templates_shown:
            desc = template_descriptions.get(template_name, "Project template")
            print(f"  - {template_name}.md ({desc})")

        # Show capability files if requested
        if with_capabilities:
            capability_result = copy_capability_templates(
                current_dir,
                current_dir.name,
                dry_run=True,
                capabilities_config=capabilities_config,
            )

        return {"status": "success", "dry_run": True}


def interactive_setup_wizard():
    """Interactive wizard for configuring ProtoGear setup"""
    print(
        f"\n{Colors.BOLD}{Colors.CYAN}ProtoGear Interactive Setup Wizard{Colors.ENDC}"
    )
    print("=" * 60)
    print(
        f"{Colors.GRAY}Let's configure AI-powered development workflow for your project{Colors.ENDC}"
    )
    print("=" * 60)

    config = {}

    # Detect current project
    current_dir = Path(".")
    project_info = detect_project_structure(current_dir)

    print(f"\n{Colors.CYAN}📊 Project Detection{Colors.ENDC}")
    print("-" * 30)
    print(f"Directory: {Colors.BOLD}{current_dir.absolute()}{Colors.ENDC}")

    if project_info["detected"]:
        print(f"Type: {Colors.GREEN}{project_info['type']}{Colors.ENDC}")
        if project_info.get("framework"):
            print(f"Framework: {Colors.GREEN}{project_info['framework']}{Colors.ENDC}")
    else:
        print(f"Type: {Colors.YELLOW}Generic Project{Colors.ENDC}")

    # Check Git configuration
    git_config = detect_git_config()
    if git_config["is_git_repo"]:
        print(f"Git: {Colors.GREEN}Initialized{Colors.ENDC}")
        if git_config["has_remote"]:
            print(f"Remote: {Colors.GREEN}{git_config['remote_name']}{Colors.ENDC}")
            # Show GitHub CLI status
            if git_config["has_gh_cli"]:
                print(
                    f"GitHub CLI: {Colors.GREEN}Installed{Colors.ENDC} (automated PRs available)"
                )
            else:
                print(
                    f"GitHub CLI: {Colors.YELLOW}Not detected{Colors.ENDC} (manual PRs via web)"
                )
        else:
            print(f"Remote: {Colors.YELLOW}None (local-only){Colors.ENDC}")

        # Display workflow mode
        workflow_modes = {
            "local_only": (Colors.YELLOW, "Local-Only Workflow"),
            "remote_manual": (Colors.CYAN, "Remote Workflow (Manual PRs)"),
            "remote_automated": (Colors.GREEN, "Remote Workflow (Automated PRs)"),
        }
        mode_color, mode_desc = workflow_modes.get(
            git_config.get("workflow_mode", "local_only"), (Colors.GRAY, "Unknown")
        )
        print(f"Workflow Mode: {mode_color}{mode_desc}{Colors.ENDC}")
    else:
        print(f"Git: {Colors.YELLOW}Not initialized{Colors.ENDC}")

    # Question 0: Project Specifications document
    specs_dest = current_dir / "PROJECT_SPECIFICATIONS.md"
    if not specs_dest.exists():
        print(f"\n{Colors.CYAN}📄 Project Description{Colors.ENDC}")
        print("-" * 30)
        print("No PROJECT_SPECIFICATIONS.md found.")
        print("Enter a brief description of your project (1-3 sentences).")
        print(
            f"{Colors.GRAY}Proto Gear will create a stub for agents to expand.{Colors.ENDC}"
        )
        description = safe_input(
            f"\n{Colors.BOLD}Project description (or Enter to skip): {Colors.ENDC}"
        ).strip()
        if description:
            config["project_description"] = description

    # Question 1: Branching Strategy
    print(f"\n{Colors.CYAN}📋 Branching & Git Workflow{Colors.ENDC}")
    print("-" * 30)
    print("Proto Gear can generate a comprehensive branching strategy document")
    print("that defines Git workflow conventions and commit message standards.")
    print(f"\n{Colors.GRAY}This includes:{Colors.ENDC}")
    print("  • Branch naming conventions (feature/*, bugfix/*, hotfix/*)")
    print("  • Conventional commit message format")
    print("  • Workflow examples for AI agents")
    print("  • PR templates and merge strategies")

    if git_config["is_git_repo"]:
        print(
            f"\n{Colors.GREEN}✓ Git repository detected - branching strategy recommended{Colors.ENDC}"
        )
    else:
        print(
            f"\n{Colors.YELLOW}⚠ No Git repository - you can still generate the strategy for future use{Colors.ENDC}"
        )

    while True:
        response = safe_input(
            f"\n{Colors.BOLD}Generate BRANCHING.md? (y/n): {Colors.ENDC}"
        ).lower()
        if response in ["y", "yes"]:
            config["with_branching"] = True
            break
        elif response in ["n", "no"]:
            config["with_branching"] = False
            break
        else:
            print(f"{Colors.YELLOW}Please enter 'y' or 'n'{Colors.ENDC}")

    # Question 2: Ticket Prefix (only if branching enabled)
    if config["with_branching"]:
        print(f"\n{Colors.CYAN}🎫 Ticket Prefix Configuration{Colors.ENDC}")
        print("-" * 30)
        print("Tickets and branches use a prefix for identification.")
        print(f"{Colors.GRAY}Examples: PROJ-001, APP-042, MYAPP-123{Colors.ENDC}")

        # Suggest a prefix based on project name
        suggested_prefix = (
            current_dir.name.upper().replace("-", "").replace("_", "")[:6]
        )
        if not suggested_prefix or len(suggested_prefix) < 2:
            suggested_prefix = "PROJ"

        print(f"\nSuggested prefix: {Colors.GREEN}{suggested_prefix}{Colors.ENDC}")

        response = (
            safe_input(
                f"{Colors.BOLD}Enter ticket prefix (press Enter for '{suggested_prefix}'): {Colors.ENDC}"
            )
            .strip()
            .upper()
        )

        if response:
            # Validate prefix (alphanumeric, 2-10 chars)
            if response.isalnum() and 2 <= len(response) <= 10:
                config["ticket_prefix"] = response
            else:
                print(
                    f"{Colors.YELLOW}Invalid prefix. Using suggested: {suggested_prefix}{Colors.ENDC}"
                )
                config["ticket_prefix"] = suggested_prefix
        else:
            config["ticket_prefix"] = suggested_prefix

        print(f"Using prefix: {Colors.GREEN}{config['ticket_prefix']}{Colors.ENDC}")
    else:
        config["ticket_prefix"] = None

    # Summary
    print(f"\n{Colors.BOLD}{Colors.CYAN}📝 Configuration Summary{Colors.ENDC}")
    print("=" * 60)
    print(f"Project: {Colors.BOLD}{current_dir.name}{Colors.ENDC}")
    print(f"Type: {project_info.get('type', 'Generic')}")
    if project_info.get("framework"):
        print(f"Framework: {project_info['framework']}")

    print(f"\n{Colors.CYAN}Files to be created:{Colors.ENDC}")
    print(f"  {Colors.GREEN}✓{Colors.ENDC} AGENTS.md (AI agent integration guide)")
    print(f"  {Colors.GREEN}✓{Colors.ENDC} PROJECT_STATUS.md (Project state tracking)")

    if config["with_branching"]:
        print(f"  {Colors.GREEN}✓{Colors.ENDC} BRANCHING.md (Git workflow conventions)")
        print(f"\nTicket Prefix: {Colors.BOLD}{config['ticket_prefix']}{Colors.ENDC}")
    else:
        print(f"  {Colors.GRAY}⊘ BRANCHING.md (not selected){Colors.ENDC}")

    # Confirmation
    print()
    while True:
        response = safe_input(
            f"{Colors.BOLD}Proceed with setup? (y/n): {Colors.ENDC}"
        ).lower()
        if response in ["y", "yes"]:
            config["confirmed"] = True
            break
        elif response in ["n", "no"]:
            config["confirmed"] = False
            break
        else:
            print(f"{Colors.YELLOW}Please enter 'y' or 'n'{Colors.ENDC}")

    return config


def run_simple_protogear_init(
    dry_run=False,
    force=False,
    with_branching=False,
    ticket_prefix=None,
    with_capabilities=False,
    capabilities_config=None,
    with_all=False,
    core_templates=None,
    project_description=None,
):
    """
    Initialize ProtoGear AI Agent Framework in current project

    Args:
        dry_run: If True, don't actually write files
        force: If True, overwrite existing files without prompting
        with_branching: Generate BRANCHING.md
        ticket_prefix: Ticket ID prefix
        with_capabilities: Generate .proto-gear/ directory
        capabilities_config: Configuration for capabilities
        with_all: Generate all available templates
        core_templates: List of specific core templates to generate
    """
    from datetime import datetime

    print(f"\n{Colors.BOLD}ProtoGear AI Agent Framework Initialization{Colors.ENDC}")
    print("=" * 60)
    print(
        f"{Colors.GRAY}Adding AI-powered development workflow to your project{Colors.ENDC}"
    )
    print("=" * 60)

    # Directly run agent framework setup (no menu)
    try:
        result = setup_agent_framework_only(
            dry_run=dry_run,
            force=force,
            with_branching=with_branching,
            ticket_prefix=ticket_prefix,
            with_capabilities=with_capabilities,
            capabilities_config=capabilities_config,
            with_all=with_all,
            core_templates=core_templates,
            project_description=project_description,
        )
    except KeyboardInterrupt:
        return {"status": "cancelled"}

    # Show results
    if result["status"] == "success":
        if result.get("dry_run"):
            print(
                f"\n{Colors.GREEN}SUCCESS: Dry run completed successfully!{Colors.ENDC}"
            )
        else:
            print(
                f"\n{Colors.GREEN}SUCCESS: ProtoGear AI Agent Framework integrated!{Colors.ENDC}"
            )

            if result.get("files_created"):
                print(f"\n{Colors.CYAN}Files created:{Colors.ENDC}")

                # Separate template files from capability files
                template_files = []
                capability_files = []

                for file in result["files_created"]:
                    # Handle both forward and backslash separators
                    if file.startswith(".proto-gear/") or file.startswith(
                        ".proto-gear\\"
                    ):
                        capability_files.append(file)
                    else:
                        template_files.append(file)

                # Show templates
                for file in template_files:
                    print(f"  + {file}")

                # Show capabilities summary if any
                if capability_files:
                    print(
                        f"\n{Colors.CYAN}Capabilities installed ({len(capability_files)} files):{Colors.ENDC}"
                    )
                    print(f"  + .proto-gear/ directory with:")

                    # Categorize capability files (handle both separators)
                    skills = [
                        f
                        for f in capability_files
                        if "/skills/" in f or "\\skills\\" in f
                    ]
                    workflows = [
                        f
                        for f in capability_files
                        if "/workflows/" in f or "\\workflows\\" in f
                    ]
                    commands = [
                        f
                        for f in capability_files
                        if "/commands/" in f or "\\commands\\" in f
                    ]

                    if skills:
                        print(f"    • {len(skills)} skill(s)")
                    if workflows:
                        print(f"    • {len(workflows)} workflow(s)")
                    if commands:
                        print(f"    • {len(commands)} command(s)")

            # Dynamic next steps based on what was created
            print(f"\n{Colors.YELLOW}Next steps:{Colors.ENDC}")
            files = result.get("files_created", [])
            step = 1

            if "AGENTS.md" in files:
                print(
                    f"  {step}. Review AGENTS.md to understand AI agent patterns and workflows"
                )
                step += 1

            if "PROJECT_STATUS.md" in files:
                print(f"  {step}. Check PROJECT_STATUS.md for project state tracking")
                step += 1

            if "TESTING.md" in files:
                print(f"  {step}. Review TESTING.md for TDD methodology")
                step += 1

            if "BRANCHING.md" in files:
                print(f"  {step}. Follow BRANCHING.md conventions for Git workflow")
                step += 1

            # Check if capabilities were installed
            has_capabilities = any(
                f.startswith(".proto-gear/") or f.startswith(".proto-gear\\")
                for f in files
            )
            if has_capabilities:
                print(
                    f"  {step}. Explore .proto-gear/ for available skills, workflows, and commands"
                )
                step += 1

            print(
                f"  {step}. AI agents will read these templates and collaborate naturally"
            )

    return result


# ---------------------------------------------------------------------------
# CLI entry point
#
# Argparse construction and command dispatch live in the ``cli`` package
# (PROTO-042, ADR-001 Phase A). ``main`` is re-exported here so the public
# entry points keep working unchanged: ``proto_gear_pkg.proto_gear:main`` in
# pyproject.toml and ``from proto_gear_pkg.proto_gear import main``.
# ---------------------------------------------------------------------------
from .cli import main

if __name__ == "__main__":
    main()
